@echo off
del .\login-server.exe
del .\char-server.exe
del .\map-server.exe
del .\txt-converter.exe
del .\*.ilk
del .\*.pdb
del .\*.map
del .\src\common\zlib\*.pdb
del .\src\common\lua\*.pdb
del .\src\common\*.pdb
del .\src\char\*.pdb
del .\src\login\*.pdb
del .\src\map\*.pdb
del .\src\converter\*.pdb
del .\src\common\zlib\*.obj
del .\src\common\lua\*.obj
del .\src\common\lua\*.lib
del .\src\common\*.obj
del .\src\char\*.obj
del .\src\login\*.obj
del .\src\map\*.obj
del .\src\converter\*.obj
