/*
 * Copyright (C) 2002-2007  Auriga
 *
 * This file is part of Auriga.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street - Fifth Floor, Boston, MA 02110-1301, USA.
 *
 */

#ifndef _STATUS_H_
#define _STATUS_H_

struct status_pretimer {
	int timer;
	int target_id;
	short m;
	short type;
	int val1,val2,val3,val4;
	int tick;
	int flag;
};

// ステータス異常データベース
struct scdata_db {
	short save;
	int releasable;
	int disable;
	int copyable;
};

// パラメータ取得系
int status_get_class(struct block_list *bl);
int status_get_dir(struct block_list *bl);
int status_get_lv(struct block_list *bl);
int status_get_jlv(struct block_list *bl);
int status_get_range(struct block_list *bl);
int status_get_group(struct block_list *bl);
int status_get_hp(struct block_list *bl);
int status_get_sp(struct block_list *bl);
int status_get_max_hp(struct block_list *bl);
int status_get_max_sp(struct block_list *bl);
int status_get_str(struct block_list *bl);
int status_get_agi(struct block_list *bl);
int status_get_vit(struct block_list *bl);
int status_get_int(struct block_list *bl);
int status_get_dex(struct block_list *bl);
int status_get_luk(struct block_list *bl);
int status_get_hit(struct block_list *bl);
int status_get_flee(struct block_list *bl);
int status_get_def(struct block_list *bl);
int status_get_mdef(struct block_list *bl);
int status_get_flee2(struct block_list *bl);
int status_get_def2(struct block_list *bl);
int status_get_mdef2(struct block_list *bl);
int status_get_baseatk(struct block_list *bl);
int status_get_atk(struct block_list *bl);
int status_get_atk2(struct block_list *bl);
int status_get_speed(struct block_list *bl);
int status_get_adelay(struct block_list *bl);
int status_get_amotion(struct block_list *bl);
int status_get_dmotion(struct block_list *bl);
int status_get_element(struct block_list *bl);
int status_get_attack_element(struct block_list *bl);
int status_get_attack_element2(struct block_list *bl);
int status_get_attack_element_nw(struct block_list *bl);
#define status_get_elem_type(bl)	(status_get_element(bl)%20)
#define status_get_elem_level(bl)	(status_get_element(bl)/20)
int status_get_party_id(struct block_list *bl);
int status_get_guild_id(struct block_list *bl);
int status_get_race(struct block_list *bl);
int status_get_size(struct block_list *bl);
int status_get_mode(struct block_list *bl);
int status_get_mexp(struct block_list *bl);
int status_get_enemy_type(struct block_list *bl);
short status_get_clothes_color(struct block_list *bl);

struct status_change *status_get_sc(struct block_list *bl);

int status_get_matk1(struct block_list *bl);
int status_get_matk2(struct block_list *bl);
int status_get_critical(struct block_list *bl);
int status_get_atk_(struct block_list *bl);
int status_get_atk_2(struct block_list *bl);

// 状態異常関連
int status_can_save(int type);
int status_is_disable(int type,int mask);
int status_change_start(struct block_list *bl,int type,int val1,int val2,int val3,int val4,int tick,int flag);
int status_change_end(struct block_list* bl, int type, int tid);
int status_change_pretimer(struct block_list *bl,int type,int val1,int val2,int val3,int val4,int tick,int flag,int pre_tick);
int status_change_timer(int tid, unsigned int tick, int id, void *data);
int status_change_timer_sub(struct block_list *bl, va_list ap);
int status_change_race_end(struct block_list *bl,int type);
int status_change_soulstart(struct block_list *bl,int val1,int val2,int val3,int val4,int tick,int flag);
int status_change_soulclear(struct block_list *bl);
int status_change_elemclear(struct block_list *bl);
int status_change_resistclear(struct block_list *bl);
int status_enchant_armor_elemental_end(struct block_list *bl,int type);
int status_enchant_elemental_end(struct block_list *bl,int type);
int status_change_clear(struct block_list *bl,int type);
int status_change_release(struct block_list *bl,int mask);
int status_clearpretimer(struct block_list *bl);
int status_change_attacked_end(struct block_list *bl);
int status_change_hidden_end(struct block_list *bl);
int status_change_removemap_end(struct block_list *bl);
int status_change_rate(struct block_list *bl,int type,int rate,int src_level);
int status_change_copy(struct block_list *src,struct block_list *bl);
int status_change_addeff_start(struct block_list *src, struct block_list *bl, int id, int rate, int type, unsigned int tick);

// 状態チェック
int status_check_no_magic_damage(struct block_list *bl);

#ifdef DYNAMIC_SC_DATA
int status_calloc_sc_data(struct status_change *sc);
int status_free_sc_data(struct status_change *sc);
extern struct status_change_data dummy_sc_data[MAX_STATUSCHANGE];
#endif

// ステータス計算
int status_calc_pc(struct map_session_data* sd,int first);
int status_calc_pc_stop_begin(struct block_list *bl);
int status_calc_pc_stop_end(struct block_list *bl);
int status_get_overrefine_bonus(int lv);
int status_percentrefinery(struct map_session_data *sd,struct item *item);
int status_percentrefinery_weaponrefine(struct map_session_data *sd,struct item *item);
extern int current_equip_item_index;
extern int current_equip_name_id;

// DB再読込用
int status_readdb(void);

int do_init_status(void);

// ステータス異常番号テーブル
enum {
	SC_PROVOKE              = 0,
	SC_ENDURE               = 1,
	SC_TWOHANDQUICKEN       = 2,
	SC_CONCENTRATE          = 3,
	SC_HIDING               = 4,
	SC_CLOAKING             = 5,
	SC_ENCPOISON            = 6,
	SC_POISONREACT          = 7,
	SC_QUAGMIRE             = 8,
	SC_ANGELUS              = 9,
	SC_BLESSING             = 10,
	SC_SIGNUMCRUCIS         = 11,
	SC_INCREASEAGI          = 12,
	SC_DECREASEAGI          = 13,
	SC_SLOWPOISON           = 14,
	SC_IMPOSITIO            = 15,
	SC_SUFFRAGIUM           = 16,
	SC_ASPERSIO             = 17,
	SC_BENEDICTIO           = 18,
	SC_KYRIE                = 19,
	SC_MAGNIFICAT           = 20,
	SC_GLORIA               = 21,
	SC_AETERNA              = 22,
	SC_ADRENALINE           = 23,
	SC_WEAPONPERFECTION     = 24,
	SC_OVERTHRUST           = 25,
	SC_MAXIMIZEPOWER        = 26,
	//
	SC_TRICKDEAD            = 29,
	SC_LOUD                 = 30,
	SC_ENERGYCOAT           = 31,
	SC_PK_PENALTY           = 32,
	SC_REVERSEORCISH        = 33,
	SC_HALLUCINATION        = 34,
	//
	SC_SPEEDPOTION0         = 37,
	SC_SPEEDPOTION1         = 38,
	SC_SPEEDPOTION2         = 39,
	SC_SPEEDUP0             = 40,
	SC_SPEEDUP1             = 41,
	SC_WALKSPEED            = 42,
	SC_SLOWPOTION           = 43,
	//
	//
	//
	//
	//
	//
	//
	//
	SC_STRIPWEAPON          = 50,
	SC_STRIPSHIELD          = 51,
	SC_STRIPARMOR           = 52,
	SC_STRIPHELM            = 53,
	SC_CP_WEAPON            = 54,
	SC_CP_SHIELD            = 55,
	SC_CP_ARMOR             = 56,
	SC_CP_HELM              = 57,
	SC_AUTOGUARD            = 58,
	SC_REFLECTSHIELD        = 59,
	SC_DEVOTION             = 60,
	SC_PROVIDENCE           = 61,
	SC_DEFENDER             = 62,
	SC_SANTA                = 63,
	SC_SUMMER               = 64,
	SC_AUTOSPELL            = 65,
	//
	//
	SC_SPEARQUICKEN         = 68,
	//
	//
	//
	//
	//
	//
	//
	//
	//
	//
	//
	//
	//
	//
	//
	//
	//
	SC_EXPLOSIONSPIRITS     = 86,
	SC_STEELBODY            = 87,
	//
	SC_COMBO                = 89,
	SC_FLAMELAUNCHER        = 90,
	SC_FROSTWEAPON          = 91,
	SC_LIGHTNINGLOADER      = 92,
	SC_SEISMICWEAPON        = 93,
	//
	//
	//
	//
	//
	//
	//
	//
	//
	SC_WE_FEMALE            = 102,
	SC_AURABLADE            = 103,
	SC_PARRYING             = 104,
	SC_CONCENTRATION        = 105,
	SC_TENSIONRELAX         = 106,
	SC_BERSERK              = 107,
	//
	//
	//
	SC_ASSUMPTIO            = 110,
	//
	//
	SC_MAGICPOWER           = 113,
	SC_EDP                  = 114,
	SC_TRUESIGHT            = 115,
	SC_WINDWALK             = 116,
	SC_MELTDOWN             = 117,
	SC_CARTBOOST            = 118,
	SC_CHASEWALK            = 119,
	SC_REJECTSWORD          = 120,
	SC_MARIONETTE           = 121,
	SC_MARIONETTE2          = 122,
	//
	SC_HEADCRUSH            = 124,
	SC_JOINTBEAT            = 125,
	//
	//
	SC_STONE                = 128,
	SC_FREEZE               = 129,
	SC_STUN                 = 130,
	SC_SLEEP                = 131,
	SC_POISON               = 132,
	SC_CURSE                = 133,
	SC_SILENCE              = 134,
	SC_CONFUSION            = 135,
	SC_BLIND                = 136,
	SC_BLEED                = 137,
	//
	//
	SC_SAFETYWALL           = 140,
	SC_PNEUMA               = 141,
	//
	SC_ANKLE                = 143,
	SC_DANCING              = 144,
	SC_KEEPING              = 145,
	SC_BARRIER              = 146,
	SC_TIGERFIST            = 147,
	//
	SC_MAGICROD             = 149,
	SC_SIGHT                = 150,
	SC_RUWACH               = 151,
	SC_AUTOCOUNTER          = 152,
	SC_VOLCANO              = 153,
	SC_DELUGE               = 154,
	SC_VIOLENTGALE          = 155,
	SC_BLADESTOP_WAIT       = 156,
	SC_BLADESTOP            = 157,
	SC_EXTREMITYFIST        = 158,
	SC_GRAFFITI             = 159,
	SC_LULLABY              = 160,
	SC_RICHMANKIM           = 161,
	SC_ETERNALCHAOS         = 162,
	SC_DRUMBATTLE           = 163,
	SC_NIBELUNGEN           = 164,
	SC_ROKISWEIL            = 165,
	SC_INTOABYSS            = 166,
	SC_SIEGFRIED            = 167,
	SC_DISSONANCE           = 168,
	SC_WHISTLE              = 169,
	SC_ASSNCROS             = 170,
	SC_POEMBRAGI            = 171,
	SC_APPLEIDUN            = 172,
	SC_UGLYDANCE            = 173,
	SC_HUMMING              = 174,
	SC_DONTFORGETME         = 175,
	SC_FORTUNE              = 176,
	SC_SERVICE4U            = 177,
	SC_BASILICA             = 178,
	SC_MINDBREAKER          = 179,
	SC_SPIDERWEB            = 180,
	SC_MEMORIZE             = 181,
	SC_DPOISON              = 182,
	//
	SC_SACRIFICE            = 184,
	SC_INCATK               = 185,
	SC_INCMATK              = 186,
	SC_WEDDING              = 187,
	SC_NOCHAT               = 188,
	SC_SPLASHER             = 189,
	SC_SELFDESTRUCTION      = 190,
	SC_MAGNUM               = 191,
	SC_GOSPEL               = 192,
	SC_INCALLSTATUS         = 193,
	SC_INCHIT               = 194,
	SC_INCFLEE              = 195,
	SC_INCMHP2              = 196,
	SC_INCMSP2              = 197,
	SC_INCATK2              = 198,
	SC_INCHIT2              = 199,
	SC_INCFLEE2             = 200,
	SC_PRESERVE             = 201,
	SC_OVERTHRUSTMAX        = 202,
	SC_CHASEWALK_STR        = 203,
	SC_WHISTLE_             = 204,
	SC_ASSNCROS_            = 205,
	SC_POEMBRAGI_           = 206,
	SC_APPLEIDUN_           = 207,
	SC_HUMMING_             = 209,
	SC_DONTFORGETME_        = 210,
	SC_FORTUNE_             = 211,
	SC_SERVICE4U_           = 212,
	SC_BATTLEORDER          = 213,
	SC_REGENERATION         = 214,
	SC_BATTLEORDER_DELAY	= 215,
	SC_REGENERATION_DELAY	= 216,
	SC_RESTORE_DELAY		= 217,
	SC_EMERGENCYCALL_DELAY	= 218,
	//
	SC_THE_MAGICIAN         = 220,
	SC_STRENGTH             = 221,
	SC_THE_DEVIL            = 222,
	SC_THE_SUN              = 223,
	SC_MEAL_INCSTR          = 224,
	SC_MEAL_INCAGI          = 225,
	SC_MEAL_INCVIT          = 226,
	SC_MEAL_INCINT          = 227,
	SC_MEAL_INCDEX          = 228,
	SC_MEAL_INCLUK          = 229,
	SC_RUN                  = 230,
	SC_SPURT                = 231,
	SC_TKCOMBO              = 232,
	SC_DODGE                = 233,
	SC_HERMODE              = 234,
	SC_TRIPLEATTACK_RATE_UP = 235,
	SC_COUNTER_RATE_UP      = 236,
	SC_WARM                 = 237,
	SC_SEVENWIND            = 238,
	//
	SC_SUN_COMFORT          = 240,
	SC_MOON_COMFORT         = 241,
	SC_STAR_COMFORT         = 242,
	SC_FUSION               = 243,
	SC_ALCHEMIST            = 244,
	SC_MONK                 = 245,
	SC_STAR                 = 246,
	SC_SAGE                 = 247,
	SC_CRUSADER             = 248,
	SC_SUPERNOVICE          = 249,
	SC_KNIGHT               = 250,
	SC_WIZARD               = 251,
	SC_PRIEST               = 252,
	SC_BARDDANCER           = 253,
	SC_ROGUE                = 254,
	SC_ASSASIN              = 255,
	SC_BLACKSMITH           = 256,
	SC_HUNTER               = 257,
	SC_SOULLINKER           = 258,
	SC_HIGH                 = 259,
	SC_DEATHKINGHT          = 260,
	SC_COLLECTOR            = 261,
	SC_NINJA                = 262,
	SC_GUNNER               = 263,
	SC_KAIZEL               = 264,
	SC_KAAHI                = 265,
	SC_KAUPE                = 266,
	SC_KAITE                = 267,
	SC_SMA                  = 268,
	SC_SWOO                 = 269,
	SC_SKE                  = 270,
	SC_SKA                  = 271,
	SC_ONEHAND              = 272,
	SC_READYSTORM           = 273,
	SC_READYDOWN            = 274,
	SC_READYTURN            = 275,
	SC_READYCOUNTER         = 276,
	SC_DODGE_DELAY          = 277,
	SC_AUTOBERSERK          = 278,
	//
	SC_DOUBLECASTING        = 280,
	SC_ELEMENTFIELD         = 281,
	SC_DARKELEMENT          = 282,
	SC_ATTENELEMENT         = 283,
	SC_MIRACLE              = 284,
	SC_ANGEL                = 285,
	SC_FORCEWALKING         = 286,
	SC_DOUBLE               = 287,
	//
	SC_BABY                 = 289,
	SC_LONGINGFREEDOM       = 290,
	SC_SHRINK               = 291,
	SC_CLOSECONFINE         = 292,
	SC_SIGHTBLASTER         = 293,
	SC_ELEMENTWATER         = 294,
	SC_MEAL_INCHIT          = 295,
	SC_MEAL_INCFLEE         = 296,
	SC_MEAL_INCFLEE2        = 297,
	SC_MEAL_INCCRITICAL     = 298,
	SC_MEAL_INCDEF          = 299,
	SC_MEAL_INCMDEF         = 300,
	SC_MEAL_INCATK          = 301,
	SC_MEAL_INCMATK         = 302,
	SC_MEAL_INCEXP          = 303,
	SC_MEAL_INCJOB          = 304,
	SC_ELEMENTGROUND        = 305,
	SC_ELEMENTFIRE          = 306,
	SC_ELEMENTWIND          = 307,
	SC_WINKCHARM            = 308,
	SC_ELEMENTPOISON        = 309,
	SC_ELEMENTDARK          = 310,
	SC_ELEMENTELEKINESIS    = 311,
	SC_ELEMENTUNDEAD        = 312,
	SC_UNDEADELEMENT        = 313,
	SC_ELEMENTHOLY          = 314,
	SC_NPC_DEFENDER         = 315,
	SC_RESISTWATER          = 316,
	SC_RESISTGROUND         = 317,
	SC_RESISTFIRE           = 318,
	SC_RESISTWIND           = 319,
	SC_RESISTPOISON         = 320,
	SC_RESISTHOLY           = 321,
	SC_RESISTDARK           = 322,
	SC_RESISTTELEKINESIS    = 323,
	SC_RESISTUNDEAD         = 324,
	SC_RESISTALL            = 325,
	SC_RACEUNKNOWN          = 326,
	SC_RACEUNDEAD           = 327,
	SC_RACEBEAST            = 328,
	SC_RACEPLANT            = 329,
	SC_RACEINSECT           = 330,
	SC_RACEFISH             = 332,
	SC_RACEDEVIL            = 333,
	SC_RACEHUMAN            = 334,
	SC_RACEANGEL            = 335,
	SC_RACEDRAGON           = 336,
	SC_TIGEREYE             = 337,
	SC_GRAVITATION_USER     = 338,
	SC_GRAVITATION          = 339,
	SC_FOGWALL              = 340,
	SC_FOGWALLPENALTY       = 341,
	//
	//
	SC_STOP                 = 344,
	SC_INVISIBLE            = 345,
	SC_MODECHANGE           = 346,
	SC_FLING                = 347,
	SC_MADNESSCANCEL        = 348,
	SC_ADJUSTMENT           = 349,
	SC_INCREASING           = 350,
	SC_DISARM               = 351,
	SC_GATLINGFEVER         = 352,
	SC_FULLBUSTER           = 353,
	SC_TATAMIGAESHI         = 354,
	SC_UTSUSEMI             = 355,
	SC_BUNSINJYUTSU         = 356,
	SC_SUITON               = 357,
	SC_NEN                  = 358,
	SC_AVOID                = 359,
	SC_CHANGE               = 360,
	SC_DEFENCE              = 361,
	SC_BLOODLUST            = 362,
	SC_FLEET                = 363,
	SC_SPEED                = 364,
	SC_ADRENALINE2          = 365,
	SC_STATUS_UNCHANGE      = 366,
	SC_INCDAMAGE            = 367,
	SC_COMBATHAN            = 368,
	SC_LIFEINSURANCE        = 369,
	SC_ITEMDROPRATE         = 370,
	SC_BOSSMAPINFO          = 371,
	SC_MEAL_INCSTR2         = 372,
	SC_MEAL_INCAGI2         = 373,
	SC_MEAL_INCVIT2         = 374,
	SC_MEAL_INCINT2         = 375,
	SC_MEAL_INCDEX2         = 376,
	SC_MEAL_INCLUK2         = 377,
	SC_SLOWCAST             = 378,
	SC_CRITICALWOUND        = 379,
	SC_MAGICMIRROR          = 380,
	SC_STONESKIN            = 381,
	SC_ANTIMAGIC            = 382,
	SC_WEAPONQUICKEN        = 383,
	SC_HAPPY                = 384,
	SC_NATURAL_HEAL_STOP    = 385,
	SC_REBIRTH              = 386,
	SC_HELLPOWER			= 387,
	SC_ENCHANTBLADE			= 388,
	SC_BERKANA				= 389,
	SC_NAUTHIZ				= 390,
	SC_TURISUSS				= 391,
	SC_HAGALAZ				= 392,
	SC_ISHA					= 393,
	SC_EISIR				= 394,
	SC_URUZ					= 395,
	SC_DEATHBOUND			= 396,
	SC_FEAR					= 397,
	SC_VENOMIMPRESS			= 398,
	SC_POISONINGWEAPON		= 399,
	SC_WEAPONBLOCKING		= 400,
	SC_WEAPONBLOCKING2		= 401,
	SC_CLOAKINGEXCEED		= 402,
	SC_HALLUCINATIONWALK	= 403,
	SC_HALLUCINATIONWALK2	= 404,
	SC_ROLLINGCUTTER		= 405,
	SC_TOXIN				= 406,
	SC_PARALIZE				= 407,
	SC_VENOMBLEED			= 408,
	SC_MAGICMUSHROOM		= 409,
	SC_DEATHHURT			= 410,
	SC_PYREXIA				= 411,
	SC_OBLIVIONCURSE		= 412,
	SC_LEECHEND				= 413,
	SC_EPICLESIS			= 414,
	SC_ORATIO				= 415,
	SC_LAUDAAGNUS			= 416,
	SC_LAUDARAMUS			= 417,
	SC_RENOVATIO			= 418,
	SC_EXPIATIO				= 419,
	SC_DUPLELIGHT			= 420,
	SC_SACRAMENT			= 421,
	SC_WHITEIMPRISON		= 422,
	SC_FROSTMISTY			= 423,
	SC_MARSHOFABYSS			= 424,
	SC_RECOGNIZEDSPELL		= 425,
	SC_STASIS				= 426,
	SC_HELLINFERNO			= 427,
	SC_SUMMONBALL1			= 428,
	SC_SUMMONBALL2			= 429,
	SC_SUMMONBALL3			= 430,
	SC_SUMMONBALL4			= 431,
	SC_SUMMONBALL5			= 432,
	SC_SPELLBOOK			= 433,
	SC_FEARBREEZE			= 434,
	SC_ELECTRICSHOCKER		= 435,
	SC_WUGDASH				= 436,
	SC_WUGBITE				= 437,
	SC_CAMOUFLAGE			= 438,
	SC_ACCELERATION			= 439,
	SC_HOVERING				= 440,
	SC_OVERHEAT				= 441,
	SC_SHAPESHIFT			= 442,
	SC_INFRAREDSCAN			= 443,
	SC_ANALYZE				= 444,
	SC_MAGNETICFIELD		= 445,
	SC_NEUTRALBARRIER_USER	= 446,
	SC_NEUTRALBARRIER		= 447,
	SC_STEALTHFIELD_USER	= 448,
	SC_STEALTHFIELD			= 449,
	SC_MANU_ATK				= 450,
	SC_MANU_DEF				= 451,
	SC_MANU_MATK			= 452,
	SC_SPL_ATK				= 453,
	SC_SPL_DEF				= 454,
	SC_SPL_MATK				= 455,
	SC__REPRODUCE			= 456,
	SC__AUTOSHADOWSPELL		= 457,
	SC__SHADOWFORM			= 458,
	SC__BODYPAINT			= 459,
	SC__INVISIBILITY		= 460,
	SC__DEADLYINFECT		= 461,
	SC__ENERVATION			= 462,
	SC__GROOMY				= 463,
	SC__IGNORANCE			= 464,
	SC__LAZINESS			= 465,
	SC__UNLUCKY				= 466,
	SC__WEAKNESS			= 467,
	SC__STRIPACCESSARY		= 468,
	SC__MANHOLE				= 469,
	SC__BLOODYLUST			= 470,
	SC_REFLECTDAMAGE		= 471,
	SC_FORCEOFVANGUARD		= 472,
	SC_SHIELDSPELL_DEF		= 473,
	SC_SHIELDSPELL_MDEF		= 474,
	SC_SHIELDSPELL_REF		= 475,
	SC_EXEEDBREAK			= 476,
	SC_PRESTIGE				= 477,
	SC_BANDING				= 478,
	SC_SITDOWN_FORCE		= 479,
	SC_EARTHDRIVE			= 480,
	SC_INSPIRATION			= 481,
	SC_FALLENEMPIRE			= 482,
	SC_CRESCENTELBOW		= 483,
	SC_CURSEDCIRCLE_USER	= 484,
	SC_CURSEDCIRCLE			= 485,
	SC_LIGHTNINGWALK		= 486,
	SC_RAISINGDRAGON		= 487,
	SC_GENTLETOUCH_ENERGYGAIN	= 488,
	SC_GENTLETOUCH_CHANGE	= 489,
	SC_GENTLETOUCH_REVITALIZE	= 490,
	SC_SWING				= 491,
	SC_SYMPHONY_LOVE		= 492,
	SC_MOONLIT_SERENADE		= 493,
	SC_RUSH_WINDMILL		= 494,
	SC_ECHOSONG				= 495,
	SC_HARMONIZE			= 496,
	SC_NETHERWORLD			= 497,
	SC_SIREN				= 498,
	SC_DEEP_SLEEP			= 499,
	SC_SIRCLEOFNATURE		= 500,
	SC_GLOOMYDAY			= 501,
	SC_SONG_OF_MANA			= 502,
	SC_DANCE_WITH_WUG		= 503,
	SC_SATURDAY_NIGHT_FEVER	= 504,
	SC_LERADS_DEW			= 505,
	SC_MELODYOFSINK			= 506,
	SC_BEYOND_OF_WARCRY		= 507,
	SC_UNLIMITED_HUMMING_VOICE	= 508,
	SC_PROPERTYWALK			= 509,
	SC_SPELLFIST			= 510,
	SC_DIAMONDDUST			= 511,
	SC_CLOUD_KILL			= 512,
	SC_STRIKING				= 513,
	SC_WARMER				= 514,
	SC_VACUUM_EXTREME		= 515,
	SC_GN_CARTBOOST			= 516,
	SC_THORNS_TRAP			= 517,
	SC_BLOOD_SUCKER			= 518,
	SC_SPORE_EXPLOSION		= 519,
	SC_FIRE_EXPANSION_SMOKE_POWDER	= 520,
	SC_FIRE_EXPANSION_TEAR_GAS	= 521,
	SC_MANDRAGORA			= 522,
	SC_MELON_BOMB			= 523,
	SC_BANANA_BOMB			= 524,
	SC_MYSTERIOUS_POWDER	= 525,
	SC_BOOST500				= 526,
	SC_FULL_SWING_K			= 527,
	SC_MANA_PLUS			= 528,
	SC_MUSTLE_M				= 529,
	SC_LIFE_FORCE_F			= 530,
	SC_PROMOTE_HEALTH_RESERCH	= 531,
	SC_ENERGY_DRINK_RESERCH	= 532,
	SC_EXTRACT_WHITE_POTION_Z	= 533,
	SC_VITATA_500			= 534,
	SC_EXTRACT_SALAMINE_JUICE	= 535,
	SC_SAVAGE_STEAK			= 536,
	SC_COCKTAIL_WARG_BLOOD	= 537,
	SC_MINOR_BBQ			= 538,
	SC_SIROMA_ICE_TEA		= 539,
	SC_DROCERA_HERB_STEAMED	= 540,
	SC_PUTTI_TAILS_NOODLES	= 541,
	SC_STOMACHACHE			= 542,
	SC_MONSTER_TRANSFORM	= 543,
	SC_IZAYOI				= 544,
	SC_KG_KAGEHUMI			= 545,
	SC_KYOMU				= 546,
	SC_KAGEMUSYA			= 547,
	SC_AKAITSUKI			= 548,
	SC_ALL_RIDING			= 549,
	SC_MEIKYOUSISUI			= 550,
	SC_KYOUGAKU				= 551,
	SC_ODINS_POWER			= 552,
	SC_JOB_COMBATHAN		= 553,
	SC_MER_FLEE				= 554,
	SC_MER_ATK				= 555,
	SC_MER_HP				= 556,
	SC_MER_SP				= 557,
	SC_MER_HIT				= 558,
	SC_ON_PUSH_CART			= 559,
	SC_KO_ZENKAI			= 560,
	SC_KO_JYUMONJIKIRI		= 561,
	SC_SUMMON_ELEM			= 562,
	SC_CIRCLE_OF_FIRE		= 563,
	SC_CIRCLE_OF_FIRE_OPTION	= 564,
	SC_FIRE_CLOAK			= 565,
	SC_FIRE_CLOAK_OPTION	= 566,
	SC_WATER_SCREEN			= 567,
	SC_WATER_SCREEN_OPTION	= 568,
	SC_WATER_DROP			= 569,
	SC_WATER_DROP_OPTION	= 570,
	SC_WATER_BARRIER		= 571,
	SC_WIND_STEP			= 572,
	SC_WIND_STEP_OPTION		= 573,
	SC_WIND_CURTAIN			= 574,
	SC_WIND_CURTAIN_OPTION	= 575,
	SC_ZEPHYR				= 576,
	SC_SOLID_SKIN			= 577,
	SC_SOLID_SKIN_OPTION	= 578,
	SC_STONE_SHIELD			= 579,
	SC_STONE_SHIELD_OPTION	= 580,
	SC_POWER_OF_GAIA		= 581,
	SC_PYROTECHNIC			= 582,
	SC_PYROTECHNIC_OPTION	= 583,
	SC_HEATER				= 584,
	SC_HEATER_OPTION		= 585,
	SC_TROPIC				= 586,
	SC_TROPIC_OPTION		= 587,
	SC_AQUAPLAY				= 588,
	SC_AQUAPLAY_OPTION		= 589,
	SC_COOLER				= 590,
	SC_COOLER_OPTION		= 591,
	SC_CHILLY_AIR			= 592,
	SC_CHILLY_AIR_OPTION	= 593,
	SC_GUST					= 594,
	SC_GUST_OPTION			= 595,
	SC_BLAST				= 596,
	SC_BLAST_OPTION			= 597,
	SC_WILD_STORM			= 598,
	SC_WILD_STORM_OPTION	= 599,
	SC_PETROLOGY			= 600,
	SC_PETROLOGY_OPTION		= 601,
	SC_CURSED_SOIL			= 602,
	SC_CURSED_SOIL_OPTION	= 603,
	SC_UPHEAVAL				= 604,
	SC_UPHEAVAL_OPTION		= 605,
	SC_TIDAL_WEAPON			= 606,
	SC_TIDAL_WEAPON_OPTION	= 607,
	SC_ROCK_CRUSHER			= 608,
	SC_ROCK_CRUSHER_ATK		= 609,
	SC_FIRE_INSIGNIA		= 610,
	SC_WATER_INSIGNIA		= 611,
	SC_WIND_INSIGNIA		= 612,
	SC_EARTH_INSIGNIA		= 613,
	SC_HAT_EFFECT			= 614,
	SC_JP_EVENT01			= 615,
	SC_JP_EVENT02			= 616,
	SC_JP_EVENT03			= 617,
	SC_JP_EVENT04			= 618,
	SC_ACTIVE_MONSTER_TRANSFORM	= 619,
	SC_INVINCIBLE			= 620,
	SC_INVINCIBLEOFF		= 621,
	SC_RAID					= 622,
	SC_ZANGETSU				= 623,
	SC_GENSOU				= 624,
	SC_ASSUMPTIO2			= 625,
	SC_PHI_DEMON			= 626,
	SC_ATKPOTION			= 627,
	SC_MATKPOTION			= 628,
	SC_ALMIGHTY				= 629,
	SC_DARKCROW				= 630,
	SC_UNLIMIT				= 631,
	SC_ILLUSIONDOPING		= 632,
	SC_FRIGG_SONG			= 633,
	SC_OFFERTORIUM			= 634,
	SC_TELEKINESIS_INTENSE	= 635,
	SC_KINGS_GRACE			= 636,
	SC_FULL_THROTTLE		= 637,
	SC_REBOUND				= 638,
	SC__ESCAPE				= 639,
	SC_SUHIDE				= 640,
	SC_SU_STOOP				= 641,
	SC_CATNIPPOWDER			= 642,
	SC_SV_ROOTTWIST			= 643,
	SC_BITESCAR				= 644,
	SC_ARCLOUSEDASH			= 645,
	SC_TUNAPARTY			= 646,
	SC_SHRIMP				= 647,
	SC_FRESHSHRIMP			= 648,
	SC_HISS					= 649,
	SC_NYANGGRASS			= 650,
	SC_CHATTERING			= 651,
	SC_GROOMING				= 652,
	SC_PROTECTIONOFSHRIMP	= 653,
	SC_SPIRITOFLAND			= 654,

	// startでは使えないresistをアイテム側で全てクリアするための物
	SC_RESISTCLEAR          = 1001,
	SC_RACECLEAR            = 1002,
	SC_SOUL                 = 1003,
	SC_SOULCLEAR            = 1004,
};

// 状態アイコン
// 厳密にはキャラクターの色の変化なども含まれている(爆裂波動など)
enum {
	SI_BLANK            = 43,

	SI_PROVOKE          = 0,
	SI_ENDURE           = 1,
	SI_TWOHANDQUICKEN   = 2,
	SI_CONCENTRATE      = 3,
	SI_HIDING           = 4,
	SI_CLOAKING         = 5,
	SI_ENCPOISON        = 6,
	SI_POISONREACT      = 7,
	SI_QUAGMIRE         = 8,
	SI_ANGELUS          = 9,
	SI_BLESSING         = 10,
	SI_SIGNUMCRUCIS     = 11,
	SI_INCREASEAGI      = 12,
	SI_DECREASEAGI      = 13,
	SI_SLOWPOISON       = 14,
	SI_IMPOSITIO        = 15,
	SI_SUFFRAGIUM       = 16,
	SI_ASPERSIO         = 17,
	SI_BENEDICTIO       = 18,
	SI_KYRIE            = 19,
	SI_MAGNIFICAT       = 20,
	SI_GLORIA           = 21,
	SI_AETERNA          = 22,
	SI_ADRENALINE       = 23,
	SI_WEAPONPERFECTION = 24,
	SI_OVERTHRUST       = 25,
	SI_MAXIMIZEPOWER    = 26,
	SI_RIDING           = 27,
	SI_FALCON           = 28,
	SI_TRICKDEAD        = 29,
	SI_LOUD             = 30,
	SI_ENERGYCOAT       = 31,
	SI_BREAKARMOR       = 32,
	SI_BREAKWEAPON      = 33,
	SI_HALLUCINATION    = 34,
	SI_WEIGHT50         = 35,
	SI_WEIGHT90         = 36,
	SI_SPEEDPOTION0     = 37,
	SI_SPEEDPOTION1     = 38,
	SI_SPEEDPOTION2     = 39,
	//SI_ATTHASTEINFINITY= 40,
	SI_MOVHASTE_POT     = 41,
	SI_MOVHASTE_INFINITY= 42,
	//SI_AUTOCOUNTER    = 43,
	//SI_SPLASHER       = 44,
	//SI_ANKLESNARE     = 45,
	SI_ACTIONDELAY      = 46,
	//SI_NOACTION       = 47,
	//SI_IMPOSSIBLEPICKUP=48,
	//SI_BARRIER        = 49,
	SI_STRIPWEAPON      = 50,
	SI_STRIPSHIELD      = 51,
	SI_STRIPARMOR       = 52,
	SI_STRIPHELM        = 53,
	SI_CP_WEAPON        = 54,
	SI_CP_SHIELD        = 55,
	SI_CP_ARMOR         = 56,
	SI_CP_HELM          = 57,
	SI_AUTOGUARD        = 58,
	SI_REFLECTSHIELD    = 59,
	SI_DEVOTION         = 60,
	SI_PROVIDENCE       = 61,
	SI_DEFENDER         = 62,
	//SI_MAGICROD       = 63,
	//SI_WEAPONPROPERTY = 64,
	SI_AUTOSPELL        = 65,
	//SI_SPECIALZONE    = 66,
	//SI_MASK           = 67,
	SI_SPEARQUICKEN     = 68,
	//SI_BDPLAYING      = 69,
	//SI_WHISTLE        = 70,
	//SI_ASSASSINCROSS  = 71,
	//SI_POEMBRAGI      = 72,
	//SI_APPLEIDUN      = 73,
	//SI_HUMMING        = 74,
	//SI_DONTFORGETME   = 75,
	//SI_FORTUNEKISS    = 76,
	//SI_SERVICEFORYOU  = 77,
	//SI_RICHMANKIM     = 78,
	//SI_ETERNALCHAOS   = 79,
	//SI_DRUMBATTLEFIELD= 80,
	//SI_RINGNIBELUNGEN = 81,
	//SI_ROKISWEIL      = 82,
	//SI_INTOABYSS      = 83,
	//SI_SIEGFRIED      = 84,
	//SI_BLADESTOP      = 85,
	SI_EXPLOSIONSPIRITS = 86,
	SI_STEELBODY        = 87,
	SI_COMBO            = 89,
	SI_FLAMELAUNCHER    = 90,
	SI_FROSTWEAPON      = 91,
	SI_LIGHTNINGLOADER  = 92,
	SI_SEISMICWEAPON    = 93,
	//SI_MAGICATTACK    = 94,
	SI_STOP             = 95,
	//SI_WEAPONBRAKER   = 96,
	SI_UNDEAD           = 97,
	//SI_POWERUP        = 98,
	//SI_AGIUP          = 99,
	//SI_SIEGEMODE      = 100,
	//SI_INVISIBLE      = 101,
	SI_WE_FEMALE        = 102,
	SI_AURABLADE        = 103,
	SI_PARRYING         = 104,
	SI_CONCENTRATION    = 105,
	SI_TENSIONRELAX     = 106,
	SI_BERSERK          = 107,
	//SI_SACRIFICE      = 108,
	//SI_GOSPEL         = 109,
	SI_ASSUMPTIO        = 110,
	//SI_BASILICA       = 111,
	SI_ELEMENTFIELD     = 112,
	SI_MAGICPOWER       = 113,
	SI_EDP              = 114,
	SI_TRUESIGHT        = 115,
	SI_WINDWALK         = 116,
	SI_MELTDOWN         = 117,
	SI_CARTBOOST        = 118,
	SI_CHASEWALK        = 119,
	SI_REJECTSWORD      = 120,
	SI_MARIONETTE       = 121,
	SI_MARIONETTE2      = 122,
	SI_MOONLIT          = 123,
	SI_HEADCRUSH        = 124,
	SI_JOINTBEAT        = 125,
	//SI_MINDBREAKER    = 126,
	//SI_MEMORIZE       = 127,
	//SI_FOGWALL        = 128,
	//SI_SPIDERWEB      = 129,
	SI_BABY             = 130,
	SI_MAGNUM           = 131,
	SI_AUTOBERSERK      = 132,
	SI_RUN              = 133,
	SI_RUN_STOP         = 134,
	SI_READYSTORM       = 135,
	//SI_STORMKICK_READY= 136,
	SI_READYDOWN        = 137,
	//SI_DOWNKICK_READY = 138,
	SI_READYTURN        = 139,
	//SI_TURNKICK_READY = 140,
	SI_READYCOUNTER     = 141,
	//SI_COUNTER_READY  = 142,
	SI_DODGE            = 143,
	//SI_DODGE_READY    = 144,
	SI_SPURT            = 145,
	SI_DARKELEMENT      = 146,
	SI_ADRENALINE2      = 147,
	SI_ATTENELEMENT     = 148,
	SI_SOULLINK         = 149,
	SI_PLUSATTACKPOWER  = 150,
	SI_PLUSMAGICPOWER   = 151,
	SI_DEVIL            = 152,
	SI_KAITE            = 153,
	//SI_SWOO           = 154,
	//SI_STAR2          = 155,
	SI_KAIZEL           = 156,
	SI_KAAHI            = 157,
	SI_KAUPE            = 158,
	SI_SMA              = 159,
	SI_MIRACLE          = 160,
	SI_ONEHAND          = 161,
	//SI_FRIEND         = 162,
	//SI_FRIENDUP       = 163,
	//SI_SG_WARM        = 164,
	SI_WARM             = 165,
	//SI_WARM           = 166,
	//SI_WARM           = 167,
	//SI_EMOTION        = 168,
	SI_SUN_COMFORT      = 169,
	SI_MOON_COMFORT     = 170,
	SI_STAR_COMFORT     = 171,
	//SI_EXPUP          = 172,
	//SI_G_BATTLEORDER  = 173,
	//SI_G_REGENERATION = 174,
	//SI_G_POSTDELAY    = 175,
	//SI_RESISTHANDICAP = 176,
	//SI_MAXHPPERCENT   = 177,
	//SI_MAXSPPERCENT   = 178,
	//SI_DEFENCE        = 179,
	//SI_SLOWDOWN       = 180,
	SI_PRESERVE         = 181,
	SI_CHASEWALK_STR    = 182,
	//SI_NOTEXTREMITYFIST=183,
	SI_TIGEREYE         = 184,
	SI_MOVESLOW_POTION  = 185,
	SI_DOUBLECASTING    = 186,
	//SI_GRAVITATION    = 187,
	SI_OVERTHRUSTMAX    = 188,
	//SI_LONGING        = 189,
	//SI_HERMODE        = 190,
	SI_TAROTCARD        = 191,
	//SI_HLIF_AVOID     = 192,
	//SI_HFLI_FLEET     = 193,
	//SI_HFLI_SPEED     = 194,
	//SI_HLIF_CHANGE    = 195,
	//SI_HAMI_BLOODLUST = 196,
	SI_SHRINK           = 197,
	SI_SIGHTBLASTER     = 198,
	//SI_WINKCHARM      = 199,
	SI_CLOSECONFINE     = 200,
	SI_CLOSECONFINE2    = 201,
	//SI_DISABLEMOVE    = 202,
	SI_MADNESSCANCEL    = 203,
	SI_GATLINGFEVER     = 204,
	SI_HAPPY            = 205,
	SI_UTSUSEMI         = 206,
	SI_BUNSINJYUTSU     = 207,
	SI_NEN              = 208,
	SI_ADJUSTMENT       = 209,
	SI_INCREASING       = 210,
	//SI_NJ_SUITON      = 211,
	//SI_PET            = 212,
	//SI_MENTAL         = 213,
	//SI_EXPMEMORY      = 214,
	//SI_PERFORMANCE    = 215,
	//SI_GAIN           = 216,
	//SI_GRIFFON        = 217,
	//SI_DRIFT          = 218,
	//SI_WALLSHIFT      = 219,
	//SI_REINCARNATION  = 220,
	//SI_PATTACK        = 221,
	//SI_PSPEED         = 222,
	//SI_PDEFENSE       = 223,
	//SI_PCRITICAL      = 224,
	//SI_RANKING        = 225,
	//SI_PTRIPLE        = 226,
	//SI_DENERGY        = 227,
	//SI_WAVE1          = 228,
	//SI_WAVE2          = 229,
	//SI_WAVE3          = 230,
	//SI_WAVE4          = 231,
	//SI_DAURA          = 232,
	//SI_DFREEZER       = 233,
	//SI_DPUNISH        = 234,
	//SI_DBARRIER       = 235,
	//SI_DWARNING       = 236,
	//SI_MOUSEWHEEL     = 237,
	//SI_DGAUGE         = 238,
	//SI_DACCEL         = 239,
	//SI_DBLOCK         = 240,
	SI_MEAL_INCSTR      = 241,
	SI_MEAL_INCAGI      = 242,
	SI_MEAL_INCVIT      = 243,
	SI_MEAL_INCDEX      = 244,
	SI_MEAL_INCINT      = 245,
	SI_MEAL_INCLUK      = 246,
	SI_MEAL_INCFLEE     = 247,
	SI_MEAL_INCHIT      = 248,
	SI_MEAL_INCCRITICAL = 249,
	SI_COMBATHAN        = 250,
	SI_LIFEINSURANCE    = 251,
	SI_ITEMDROPRATE     = 252,
	SI_BOSSMAPINFO      = 253,
	//SI_DA_ENERGY      = 254,
	//SI_DA_FIRSTSLOT   = 255,
	//SI_DA_HEADDEF     = 256,
	//SI_DA_SPACE       = 257,
	//SI_DA_TRANSFORM   = 258,
	//SI_DA_ITEMREBUILD = 259,
	//SI_DA_ILLUSION    = 260,
	//SI_DA_DARKPOWER   = 261,
	//SI_DA_EARPLUG     = 262,
	//SI_DA_CONTRACT    = 263,
	//SI_DA_BLACK       = 264,
	//SI_DA_MAGICCART   = 265,
	//SI_CRYSTAL        = 266,
	//SI_DA_REBUILD     = 267,
	//SI_DA_EDARKNESS   = 268,
	//SI_DA_EGUARDIAN   = 269,
	//SI_DA_TIMEOUT     = 270,
	SI_MEAL_INCSTR2     = 271,
	SI_MEAL_INCAGI2     = 272,
	SI_MEAL_INCVIT2     = 273,
	SI_MEAL_INCINT2     = 274,
	SI_MEAL_INCDEX2     = 275,
	SI_MEAL_INCLUK2     = 276,
	SI_MER_FLEE         = 277,
	SI_MER_ATK          = 278,
	SI_MER_HP           = 279,
	SI_MER_SP           = 280,
	SI_MER_HIT          = 281,
	SI_SLOWCAST         = 282,
	//SI_MAGICMIRROR    = 283,
	//SI_STONESKIN      = 284,
	//SI_ANTIMAGIC      = 285,
	SI_CRITICALWOUND    = 286,
	//SI_NPC_DEFENDER   = 287,
	//SI_NOACTION_WAIT  = 288,
	SI_MOVHASTE_HORSE   = 289,
	//SI_PROTECT_DEF    = 290,
	//SI_PROTECT_MDEF   = 291,
	//SI_HEALPLUS       = 292,
	//SI_S_LIFEPOTION   = 293,
	//SI_L_LIFEPOTION   = 294,
	//SI_CRITICALPERCENT= 295,
	//SI_PLUSAVOIDVALUE = 296,
	//SI_ATKER_ASPD     = 297,
	//SI_TARGET_ASPD    = 298,
	//SI_ATKER_MOVESPEED= 299,
	//SI_ATKER_BLOOD    = 300,
	//SI_TARGET_BLOOD   = 301,
	//SI_ARMOR_PROPERTY = 302,
	//SI_REUSE_LIMIT_A  = 303,
	SI_HELLPOWER        = 304,
	//SI_STEAMPACK      = 305,
	//SI_REUSE_LIMIT_B  = 306,
	//SI_REUSE_LIMIT_C  = 307,
	//SI_REUSE_LIMIT_D  = 308,
	//SI_REUSE_LIMIT_E  = 309,
	//SI_REUSE_LIMIT_F  = 310,
	//SI_INVINCIBLE     = 311,
	SI_CPLUSONLYJOBEXP  = 312,
	//SI_PARTYFLEE      = 313,
	//SI_ANGEL_PROTECT  = 314,
	//SI_ENDURE_MDEF    = 315,
	SI_ENCHANTBLADE		= 316,
	//SI_DEATHBOUND     = 317,
	SI_NAUTHIZ			= 318,
	SI_THURISSUS		= 319,
	SI_HAGALAZ			= 320,
	SI_ISA				= 321,
	SI_OTHILA			= 322,
	SI_URUZ				= 323,
	//SI_REUSE_MILLENNIUMSHIELD	= 324,
	//SI_REUSE_CRUSHSTRIKE	= 325,
	//SI_REUSE_REFRESH	= 326,
	//SI_REUSE_STORMBLAST	= 327,
	SI_VENOMIMPRESS	= 328,
	//SI_EPICLESIS	= 329,
	SI_ORATIO			= 330,
	//SI__LAUDAAGNUS	= 331,
	//SI_LAUDARAMUS	= 332,
	SI_POISONINGWEAPON	= 333,
	SI_HALLUCINATIONWALK= 334,
	//SI_HALLUCINATIONWALK_POSTDELAY	= 335,
	SI_RENOVATIO		= 336,
	SI_WEAPONBLOCKING	= 337,
	//SI_WEAPONBLOCKING_POSTDELAY	= 338,
	SI_ROLLINGCUTTER	= 339,
	SI_EXPIATIO			= 340,
	//SI_POISONINGWEAPON	= 341,
	SI_TOXIN			= 342,
	SI_PARALIZE			= 343,
	SI_VENOMBLEED		= 344,
	SI_MAGICMUSHROOM	= 345,
	SI_DEATHHURT		= 346,
	SI_PYREXIA			= 347,
	SI_OBLIVIONCURSE	= 348,
	SI_LEECHEND			= 349,
	SI_DUPLELIGHT		= 350,
	SI_FROSTMISTY		= 351,
	SI_FEARBREEZE		= 352,
	//SI_ELECTRICSHOCKER	= 353,
	SI_MARSHOFABYSS		= 354,
	SI_RECOGNIZEDSPELL	= 355,
	//SI_STASIS	= 366,
	SI_WUGRIDER			= 357,
	SI_WUGDASH			= 358,
	//SI_WUGBITE	= 359,
	SI_CAMOUFLAGE		= 360,
	SI_ACCELERATION		= 361,
	SI_HOVERING			= 362,
	SI_SUMMONBALL1		= 363,
	SI_SUMMONBALL2		= 364,
	SI_SUMMONBALL3		= 365,
	SI_SUMMONBALL4		= 366,
	SI_SUMMONBALL5		= 367,
	//SI_MVPCARD_TAOGUNKA	= 368,
	//SI_MVPCARD_MISTRESS	= 369,
	//SI_MVPCARD_ORCHERO	= 370,
	//SI_MVPCARD_ORCLORD	= 371,
	//SI_OVERHEAT_LIMITPOINT	= 372,
	SI_OVERHEAT			= 373,
	SI_SHAPESHIFT		= 374,
	SI_INFRAREDSCAN		= 375,
	//SI_MAGNETICFIELD	= 376,
	SI_NEUTRALBARRIER	= 377,
	//SI_NEUTRALBARRIER_MASTER	= 378,
	SI_STEALTHFIELD		= 379,
	//SI_STEALTHFIELD_MASTER	= 380,
	SI_MANU_ATK			= 381,
	SI_MANU_DEF			= 382,
	SI_SPL_ATK			= 383,
	SI_SPL_DEF			= 384,
	SI_REPRODUCE		= 385,
	SI_MANU_MATK		= 386,
	SI_SPL_MATK			= 387,
	//SI_STR_SCROLL		= 388,
	//SI_INT_SCROLL		= 389,
	SI_REFLECTDAMAGE	= 390,
	SI_FORCEOFVANGUARD	= 391,
	//SI_BUCHEDENOEL	= 392,
	SI_AUTOSHADOWSPELL	= 393,
	SI_SHADOWFORM		= 394,
	SI_RAID				= 395,
	SI_SHIELDSPELL_DEF	= 396,
	SI_SHIELDSPELL_MDEF	= 397,
	SI_SHIELDSPELL_REF	= 398,
	SI_BODYPAINT		= 399,
	SI_EXEEDBREAK		= 400,
	//SI_ADORAMUS		= 401,
	SI_PRESTIGE			= 402,
	SI_INVISIBILITY		= 403,
	SI_DEADLYINFECT		= 404,
	SI_BANDING			= 405,
	SI_EARTHDRIVE		= 406,
	SI_INSPIRATION		= 407,
	SI_ENERVATION		= 408,
	SI_GROOMY			= 409,
	SI_RAISINGDRAGON	= 410,
	SI_IGNORANCE		= 411,
	SI_LAZINESS			= 412,
	SI_LIGHTNINGWALK	= 413,
	//SI_ACARAJE			= 414,
	SI_UNLUCKY			= 415,
	SI_CURSEDCIRCLE_ATKER	= 416,
	SI_CURSEDCIRCLE_TARGET	= 417,
	SI_WEAKNESS			= 418,
	SI_CRESCENTELBOW	= 419,
	//SI_NOEQUIPACCESSARY	= 420,
	SI_STRIPACCESSARY	= 421,
	SI_MANHOLE			= 422,
	//SI_POPECOOKIE		= 423,
	SI_FALLENEMPIRE		= 424,
	SI_GENTLETOUCH_ENERGYGAIN	= 425,
	SI_GENTLETOUCH_CHANGE		= 426,
	SI_GENTLETOUCH_REVITALIZE	= 427,
	SI_BLOODYLUST		= 428,
	SI_SWING			= 429,
	SI_SYMPHONY_LOVE	= 430,
	SI_PROPERTYWALK		= 431,
	SI_SPELLFIST		= 432,
	SI_NETHERWORLD		= 433,
	SI_SIREN			= 434,
	SI_DEEP_SLEEP		= 435,
	SI_SIRCLEOFNATURE	= 436,
	SI_DIAMONDDUST		= 437,
	SI_GLOOMYDAY		= 438,
	SI_SONG_OF_MANA		= 439,
	SI_CLOUD_KILL		= 440,
	SI_DANCE_WITH_WUG	= 441,
	SI_RUSH_WINDMILL	= 442,
	SI_ECHOSONG			= 443,
	SI_HARMONIZE		= 444,
	SI_STRIKING			= 445,
	SI_WARMER			= 446,
	SI_MOONLIT_SERENADE	= 447,
	SI_SATURDAY_NIGHT_FEVER	= 448,
	SI_SITDOWN_FORCE	= 449,
	SI_ANALYZE			= 450,
	SI_LERADS_DEW		= 451,
	SI_MELODYOFSINK		= 452,
	SI_BEYOND_OF_WARCRY	= 453,
	SI_UNLIMITED_HUMMING_VOICE	= 454,
	//SI_SPELLBOOK1		= 455,
	//SI_SPELLBOOK2		= 456,
	//SI_SPELLBOOK3		= 457,
	//SI_FREEZE_SP		= 458,
	//SI_GN_TRAINING_SWORD		= 459,
	//SI_GN_REMODELING_CART		= 460,
	SI_GN_CARTBOOST		= 461,
	//SI_FIXEDCASTINGTM_REDUCE	= 462,
	SI_THORNS_TRAP		= 463,
	SI_BLOOD_SUCKER		= 464,
	SI_SPORE_EXPLOSION	= 465,
	SI_DEMONIC_FIRE		= 466,
	SI_FIRE_EXPANSION_SMOKE_POWDER	= 467,
	SI_FIRE_EXPANSION_TEAR_GAS	= 468,
	//SI_BLOCKING_PLAY	= 469,
	SI_MANDRAGORA		= 470,
	//SI_ACTIVATE		= 471,
	SI_SACRAMENT		= 472,
	SI_ASSUMPTIO2		= 473,
	//SI_TK_SEVENWIND	= 474,
	//SI_LIMIT_ODINS_RECALL	= 475,
	SI_STOMACHACHE		= 476,
	SI_MYSTERIOUS_POWDER	= 477,
	SI_MELON_BOMB		= 478,
	//SI_BANANA_BOMB_SITDOWN_POSTDELAY	= 479,
	SI_PROMOTE_HEALTH_RESERCH	= 480,
	SI_ENERGY_DRINK_RESERCH		= 481,
	SI_EXTRACT_WHITE_POTION_Z	= 482,
	SI_VITATA_500		= 483,
	SI_EXTRACT_SALAMINE_JUICE	= 484,
	SI_BOOST500			= 485,
	SI_FULL_SWING_K		= 486,
	SI_MANA_PLUS		= 487,
	SI_MUSTLE_M			= 488,
	SI_LIFE_FORCE_F		= 489,
	SI_VACUUM_EXTREME	= 490,
	SI_SAVAGE_STEAK		= 491,
	SI_COCKTAIL_WARG_BLOOD	= 492,
	SI_MINOR_BBQ		= 493,
	SI_SIROMA_ICE_TEA	= 494,
	SI_DROCERA_HERB_STEAMED	= 495,
	SI_PUTTI_TAILS_NOODLES	= 496,
	SI_BANANA_BOMB		= 497,
	SI_SUMMON_AGNI	= 498,
	//SI_SPELLBOOK4	= 499,
	//SI_SPELLBOOK5	= 500,
	//SI_SPELLBOOK6	= 501,
	//SI_SPELLBOOK7	= 502,
	//SI_ELEMENTAL_AGGRESSIVE	= 503,
	//SI_RETURN_TO_ELDICASTES	= 504,
	//SI_BANDING_DEFENCE	= 505,
	//SI_SKELSCROLL	= 506,
	//SI_DISTRUCTIONSCROLL	= 507,
	//SI_ROYALSCROLL	= 508,
	//SI_IMMUNITYSCROLL	= 509,
	//SI_MYSTICSCROLL	= 510,
	//SI_BATTLESCROLL	= 511,
	//SI_ARMORSCROLL	= 512,
	//SI_FREYJASCROLL	= 513,
	//SI_SOULSCROLL	= 514,
	SI_CIRCLE_OF_FIRE		= 515,
	SI_CIRCLE_OF_FIRE_OPTION	= 516,
	SI_FIRE_CLOAK			= 517,
	SI_FIRE_CLOAK_OPTION	= 518,
	SI_WATER_SCREEN			= 519,
	SI_WATER_SCREEN_OPTION	= 520,
	SI_WATER_DROP			= 521,
	SI_WATER_DROP_OPTION	= 522,
	SI_WIND_STEP			= 523,
	SI_WIND_STEP_OPTION		= 524,
	SI_WIND_CURTAIN			= 525,
	SI_WIND_CURTAIN_OPTION	= 526,
	SI_WATER_BARRIER		= 527,
	SI_ZEPHYR				= 528,
	SI_SOLID_SKIN			= 529,
	SI_SOLID_SKIN_OPTION	= 530,
	SI_STONE_SHIELD			= 531,
	SI_STONE_SHIELD_OPTION	= 532,
	SI_POWER_OF_GAIA		= 533,
	//SI_EL_WAIT	= 534,
	//SI_EL_PASSIVE	= 535,
	//SI_EL_DEFENSIVE	= 536,
	//SI_EL_OFFENSIVE	= 537,
	//SI_EL_COST	= 538,
	SI_PYROTECHNIC			= 539,
	SI_PYROTECHNIC_OPTION	= 540,
	SI_HEATER				= 541,
	SI_HEATER_OPTION		= 542,
	SI_TROPIC				= 543,
	SI_TROPIC_OPTION		= 544,
	SI_AQUAPLAY				= 545,
	SI_AQUAPLAY_OPTION		= 546,
	SI_COOLER				= 547,
	SI_COOLER_OPTION		= 548,
	SI_CHILLY_AIR			= 549,
	SI_CHILLY_AIR_OPTION	= 550,
	SI_GUST					= 551,
	SI_GUST_OPTION			= 552,
	SI_BLAST				= 553,
	SI_BLAST_OPTION			= 554,
	SI_WILD_STORM			= 555,
	SI_WILD_STORM_OPTION	= 556,
	SI_PETROLOGY			= 557,
	SI_PETROLOGY_OPTION		= 558,
	SI_CURSED_SOIL			= 559,
	SI_CURSED_SOIL_OPTION	= 560,
	SI_UPHEAVAL				= 561,
	SI_UPHEAVAL_OPTION		= 562,
	SI_TIDAL_WEAPON			= 563,
	SI_TIDAL_WEAPON_OPTION	= 564,
	SI_ROCK_CRUSHER			= 565,
	SI_ROCK_CRUSHER_ATK		= 566,
	SI_FIRE_INSIGNIA		= 567,
	SI_WATER_INSIGNIA		= 568,
	SI_WIND_INSIGNIA		= 569,
	SI_EARTH_INSIGNIA		= 570,
	//SI_EQUIPED_FLOOR	= 571,
	//SI_GUARDIAN_RECALL	= 572,
	//SI_MORA_BUFF	= 573,
	//SI_REUSE_LIMIT_G	= 574,
	//SI_REUSE_LIMIT_H	= 575,
	//SI_NEEDLE_OF_PARALYZE	= 576,
	//SI_PAIN_KILLER	= 577,
	//SI_G_LIFEPOTION	= 578,
	//SI_VITALIZE_POTION	= 579,
	//SI_LIGHT_OF_REGENE	= 580,
	//SI_OVERED_BOOST	= 581,
	//SI_SILENT_BREEZE	= 582,
	SI_ODINS_POWER	= 583,
	//SI_STYLE_CHANGE	= 584,
	//SI_SONIC_CLAW_POSTDELAY	= 585,
	//SI_SILVERVEIN_RUSH_POSTDELAY	= 596,
	//SI_MIDNIGHT_FRENZY_POSTDELAY	= 597,
	//SI_GOLDENE_FERSE	= 598,
	//SI_ANGRIFFS_MODUS	= 599,
	//SI_TINDER_BREAKER	= 600,
	//SI_TINDER_BREAKER_POSTDELAY	= 601,
	//SI_CBC	= 602,
	//SI_CBC_POSTDELAY	= 603,
	//SI_EQC	= 604,
	//SI_MAGMA_FLOW	= 605,
	//SI_GRANITIC_ARMOR	= 606,
	//SI_PYROCLASTIC	= 607,
	//SI_VOLCANIC_ASH	= 608,
	//SI_SPIRITS_SAVEINFO1	= 609,
	//SI_SPIRITS_SAVEINFO2	= 610,
	//SI_MAGIC_CANDY	= 611,
	SI_ALL_RIDING	= 613,
	//SI_ALL_RIDING_REUSE_LIMIT	= 614,
	//SI_MACRO	= 615,
	//SI_MACRO_POSTDELAY	= 616,
	//SI_BEER_BOTTLE_CAP	= 617,
	//SI_OVERLAPEXPUP	= 618,
	//SI_PC_IZ_DUN05	= 619,
	//SI_CRUSHSTRIKE	= 620,
	SI_MONSTER_TRANSFORM	= 621,
	SI_SIT	= 622,
	//SI_ONAIR	= 623,
	//SI_MTF_ASPD	= 624,
	//SI_MTF_RANGEATK	= 625,
	//SI_MTF_MATK	= 626,
	//SI_MTF_MLEATKED	= 627,
	//SI_MTF_CRIDAMAGE	= 628,
	//SI_REUSE_LIMIT_MTF	= 629,
	//SI_MACRO_PERMIT	= 630,
	//SI_MACRO_PLAY	= 631,
	//SI_SKF_CAST	= 632,
	//SI_SKF_ASPD	= 633,
	//SI_SKF_ATK	= 634,
	//SI_SKF_MATK	= 635,
	//SI_REWARD_PLUSONLYJOBEXP	= 636,
	//SI_HANDICAPSTATE_NORECOVER	= 637,
	//SI_SET_NUM_DEF	= 638,
	//SI_SET_NUM_MDEF	= 639,
	//SI_SET_PER_DEF	= 640,
	//SI_SET_PER_MDEF	= 641,
	//SI_PARTYBOOKING_SEARCH_DEALY	= 642,
	//SI_PARTYBOOKING_REGISTER_DEALY	= 643,
	//SI_PERIOD_TIME_CHECK_DETECT_SKILL	= 644,
	SI_KO_JYUMONJIKIRI	= 645,
	SI_MEIKYOUSISUI	= 646,
	//SI_ATTHASTE_CASH	= 647,
	//SI_EQUIPPED_DIVINE_ARMOR	= 648,
	//SI_EQUIPPED_HOLY_ARMOR	= 649,
	//SI_2011RWC	= 650,
	SI_KYOUGAKU	= 651,
	SI_IZAYOI	= 652,
	SI_ZENKAI	= 653,
	SI_KG_KAGEHUMI	= 654,
	SI_KYOMU	= 655,
	SI_KAGEMUSYA	= 656,
	SI_ZANGETSU	= 657,
	SI_PHI_DEMON	= 658,
	SI_GENSOU	= 659,
	SI_AKAITSUKI	= 660,
	//SI_TETANY	= 661,
	//SI_GM_BATTLE	= 662,
	//SI_GM_BATTLE2	= 663,
	//SI_2011RWC_SCROLL	= 664,
	SI_ACTIVE_MONSTER_TRANSFORM	= 665,
	//SI_MYSTICPOWDER	= 666,
	//SI_ECLAGE_RECALL = 667,
	//SI_ENTRY_QUEUE_APPLY_DELAY = 668,
	//SI_REUSE_LIMIT_ECL = 669,
	//SI_M_LIFEPOTION = 670,
	//SI_ENTRY_QUEUE_NOTIFY_ADMISSION_TIME_OUT = 671,
	//SI_UNKNOWN_NAME = 672,
	SI_ON_PUSH_CART = 673,
	SI_HAT_EFFECT = 674,
	//SI_FLOWER_LEAF = 675,
	//SI_RAY_OF_PROTECTION = 676,
	//SI_GLASTHEIM_ATK = 677,
	//SI_GLASTHEIM_DEF = 678,
	//SI_GLASTHEIM_HEAL = 679,
	//SI_GLASTHEIM_HIDDEN = 680,
	//SI_GLASTHEIM_STATE = 681,
	//SI_GLASTHEIM_ITEMDEF = 682,
	//SI_GLASTHEIM_HPSP = 683,
	//SI_HOMUN_SKILL_POSTDELAY = 684,
	SI_ALMIGHTY = 685,
	//SI_GVG_GIANT = 686,
	//SI_GVG_GOLEM = 687,
	//SI_GVG_STUN = 688,
	//SI_GVG_STONE = 689,
	//SI_GVG_FREEZ = 690,
	//SI_GVG_SLEEP = 691,
	//SI_GVG_CURSE = 692,
	//SI_GVG_SILENCE = 693,
	//SI_GVG_BLIND = 694,
	//SI_CLIENT_ONLY_EQUIP_ARROW = 695,
	//SI_CLAN_INFO = 696,
	SI_JP_EVENT01 = 697,
	SI_JP_EVENT02 = 698,
	SI_JP_EVENT03 = 699,
	SI_JP_EVENT04 = 700,
	//SI_TELEPORT_FIXEDCASTINGDELAY = 701,
	//SI_GEFFEN_MAGIC1 = 702,
	//SI_GEFFEN_MAGIC2 = 703,
	//SI_GEFFEN_MAGIC3 = 704,
	//SI_QUEST_BUFF1 = 705,
	//SI_QUEST_BUFF2 = 706,
	//SI_QUEST_BUFF3 = 707,
	//SI_HANDICAPSTATE_ICEEXPLO = 710,
	//SI_FENRIR_CARD = 711,
	SI_FRIGG_SONG = 715,
	SI_OFFERTORIUM = 716,
	SI_TELEKINESIS_INTENSE = 717,
	SI_FULL_THROTTLE = 720,
	SI_REBOUND = 721,
	SI_UNLIMIT = 722,
	SI_KINGS_GRACE = 723,
	//SI_ITEM_ATKMAX = 724,
	//SI_ITEM_ATKMIN = 725,
	//SI_ITEM_MATKMAX = 726,
	//SI_ITEM_MATKMIN = 727,
	SI_DARKCROW = 730,
	//SI_2013_VALENTINE1 = 731,
	//SI_2013_VALENTINE2 = 732,
	//SI_2013_VALENTINE3 = 733,
	//SI_CHILL = 736,
	//SI_BURNT = 737,
	//SI_B_TRAP = 752,
	//SI_E_CHAIN = 753,
	//SI_E_QD_SHOT_READY = 754,
	//SI_C_MARKER = 755,
	//SI_H_MINE = 756,
	//SI_H_MINE_SPLASH = 757,
	//SI_P_ALTER = 758,
	//SI_HEAT_BARREL = 759,
	//SI_ANTI_M_BLAST = 760,
	//SI_SLUGSHOT = 761,
	//SI_SWORDCLAN = 762,
	//SI_ARCWANDCLAN = 763,
	//SI_GOLDENMACECLAN = 764,
	//SI_CROSSBOWCLAN = 765,
	//SI_PACKING_ENVELOPE1 = 766,
	//SI_PACKING_ENVELOPE2 = 767,
	//SI_PACKING_ENVELOPE3 = 768,
	//SI_PACKING_ENVELOPE4 = 769,
	//SI_PACKING_ENVELOPE5 = 770,
	//SI_PACKING_ENVELOPE6 = 771,
	//SI_PACKING_ENVELOPE7 = 772,
	//SI_PACKING_ENVELOPE8 = 773,
	//SI_PACKING_ENVELOPE9 = 774,
	//SI_PACKING_ENVELOPE10 = 775,
	//SI_GLASTHEIM_TRANS = 776,
	//SI_ZONGZI_POUCH_TRANS = 777,
	//SI_HEAT_BARREL_AFTER = 778,
	SI_DECORATION_OF_MUSIC = 779,
	//SI_OVERSEAEXPUP = 780,
	//SI_CLOWN_N_GYPSY_CARD = 781,
	//SI_OPEN_NPC_MARKET = 782,
	//SI_BEEF_RIB_STEW = 783,
	//SI_PORK_RIB_STEW = 784,
	//SI_CHUSEOK_MONDAY = 785,
	//SI_CHUSEOK_TUESDAY = 786,
	//SI_CHUSEOK_WEDNESDAY = 787,
	//SI_CHUSEOK_THURSDAY = 788,
	//SI_CHUSEOK_FRIDAY = 789,
	//SI_CHUSEOK_WEEKEND = 790,
	//SI_ALL_LIGHTGUARD = 791,
	//SI_ALL_LIGHTGUARD_COOL_TIME = 792,
	//SI_MTF_MHP = 793,
	//SI_MTF_MSP = 794,
	//SI_MTF_PUMPKIN = 795,
	//SI_MTF_HITFLEE = 796,
	//SI_MTF_CRIDAMAGE2 = 797,
	//SI_MTF_SPDRAIN = 798,
	//SI_ACUO_MINT_GUM = 799,
	//SI_S_HEALPOTION = 800,
	//SI_REUSE_LIMIT_S_HEAL_POTION = 801,
	//SI_PLAYTIME_STATISTICS = 802,
	//SI_GN_CHANGEMATERIAL_OPERATOR = 803,
	//SI_GN_MIX_COOKING_OPERATOR = 804,
	//SI_GN_MAKEBOMB_OPERATOR = 805,
	//SI_GN_S_PHARMACY_OPERATOR = 806,
	//SI_SO_EL_ANALYSIS_DISASSEMBLY_OPERATOR = 807,
	//SI_SO_EL_ANALYSIS_COMBINATION_OPERATOR = 808,
	//SI_NC_MAGICDECOY_OPERATOR = 809,
	//SI_GUILD_STORAGE = 810,
	//SI_GC_POISONINGWEAPON_OPERATOR = 811,
	//SI_WS_WEAPONREFINE_OPERATOR = 812,
	//SI_BS_REPAIRWEAPON_OPERATOR = 813,
	//SI_UNREADMAIL_CHECK = 814,
	//SI_JUMPINGCLAN = 815,
	//SI_JP_OTP = 816,
	//SI_HANDICAPTOLERANCE_LEVELGAP = 817,
	//SI_MTF_RANGEATK2 = 818,
	//SI_MTF_ASPD2 = 819,
	//SI_MTF_MATK2 = 820,
	//SI_SHOW_NPCHPBAR = 821,
	SI_FLOWERSMOKE = 822,
	SI_FSTONE = 823,
	//SI_DAILYSENDMAILCNT = 824,
	SI_QSCARABA = 825,
	SI_LJOSALFAR = 826,
	//SI_PAD_READER_KNIGHT = 827,
	//SI_PAD_READER_CRUSADER = 828,
	//SI_PAD_READER_BLACKSMITH = 829,
	//SI_PAD_READER_ALCHEMIST = 830,
	//SI_PAD_READER_ASSASSIN = 831,
	//SI_PAD_READER_ROGUE = 832,
	//SI_PAD_READER_WIZARD = 833,
	//SI_PAD_READER_SAGE = 834,
	//SI_PAD_READER_PRIEST = 835,
	//SI_PAD_READER_MONK = 836,
	//SI_PAD_READER_HUNTER = 837,
	//SI_PAD_READER_BARD = 838,
	//SI_PAD_READER_DANCER = 839,
	//SI_PAD_READER_TAEKWON = 840,
	//SI_PAD_READER_NINJA = 841,
	//SI_PAD_READER_GUNSLINGER = 842,
	//SI_PAD_READER_SUPERNOVICE = 843,
	//SI_ESSENCE_OF_TIME = 844,
	//SI_MINIGAME_ROULETTE = 845,
	//SI_MINIGAME_GOLD_POINT = 846,
	//SI_MINIGAME_SILVER_POINT = 847,
	//SI_MINIGAME_BRONZE_POINT = 848,
	SI_HAPPINESS_STAR = 849,
	//SI_SUMMEREVENT01 = 850,
	//SI_SUMMEREVENT02 = 851,
	//SI_SUMMEREVENT03 = 852,
	//SI_SUMMEREVENT04 = 853,
	//SI_SUMMEREVENT05 = 854,
	//SI_MINIGAME_ROULETTE_BONUS_ITEM = 855,
	SI_DRESS_UP = 856,
	SI_MAPLE_FALLS = 857,
	//SI_ALL_NIFLHEIM_RECALL = 858,

	//SI_MTF_MARIONETTE = 860,
	//SI_MTF_LUDE = 861,
	//SI_MTF_CRUISER = 862,
	SI_MERMAID_LONGING = 863,

	//SI_DRACULA_CARD = 865,

	//SI_LIMIT_POWER_BOOSTER = 867,

	SI_TIME_ACCESSORY = 872,
	//SI_EP16_DEF = 873,
	//SI_NORMAL_ATKED_SP = 874,
	SI_BODYSTATE_STONECURSE = 875,
	SI_BODYSTATE_FREEZING = 876,
	SI_BODYSTATE_STUN = 877,
	SI_BODYSTATE_SLEEP = 878,
	//SI_BODYSTATE_UNDEAD = 879,
	//SI_BODYSTATE_STONECURSE_ING = 880,
	SI_BODYSTATE_BURNNING = 881,
	SI_BODYSTATE_IMPRISON = 882,
	SI_HEALTHSTATE_POISON = 883,
	SI_HEALTHSTATE_CURSE = 884,
	SI_HEALTHSTATE_SILENCE = 885,
	SI_HEALTHSTATE_CONFUSION = 886,
	SI_HEALTHSTATE_BLIND = 887,
	//SI_HEALTHSTATE_ANGELUS = 888,
	//SI_HEALTHSTATE_BLOODING = 889,
	SI_HEALTHSTATE_HEAVYPOISON = 890,
	SI_HEALTHSTATE_FEAR = 891,
	//SI_CHERRY_BLOSSOM_CAKE = 892,
	SI_SU_STOOP = 893,
	SI_CATNIPPOWDER = 894,
	//SI_BLOSSOM_FLUTTERING = 895,
	SI_SV_ROOTTWIST = 896,
	//SI_ATTACK_PROPERTY_NOTHING = 897,
	//SI_ATTACK_PROPERTY_WATER = 898,
	//SI_ATTACK_PROPERTY_GROUND = 899,
	//SI_ATTACK_PROPERTY_FIRE = 900,
	//SI_ATTACK_PROPERTY_WIND = 901,
	//SI_ATTACK_PROPERTY_POISON = 902,
	//SI_ATTACK_PROPERTY_SAINT = 903,
	//SI_ATTACK_PROPERTY_DARKNESS = 904,
	//SI_ATTACK_PROPERTY_TELEKINESIS = 905,
	//SI_ATTACK_PROPERTY_UNDEAD = 906,
	//SI_RESIST_PROPERTY_NOTHING = 907,
	//SI_RESIST_PROPERTY_WATER = 908,
	//SI_RESIST_PROPERTY_GROUND = 909,
	//SI_RESIST_PROPERTY_FIRE = 910,
	//SI_RESIST_PROPERTY_WIND = 911,
	//SI_RESIST_PROPERTY_POISON = 912,
	//SI_RESIST_PROPERTY_SAINT = 913,
	//SI_RESIST_PROPERTY_DARKNESS = 914,
	//SI_RESIST_PROPERTY_TELEKINESIS = 915,
	//SI_RESIST_PROPERTY_UNDEAD = 916,
	SI_BITESCAR = 917,
	SI_ARCLOUSEDASH = 918,
	SI_TUNAPARTY = 919,
	SI_SHRIMP = 920,
	SI_FRESHSHRIMP = 921,
	//SI_PERIOD_RECEIVEITEM = 922,
	//SI_PERIOD_PLUSEXP = 923,
	//SI_PERIOD_PLUSJOBEXP = 924,
	//SI_RUNEHELM = 925,
	//SI_HELM_VERKANA = 926,
	//SI_HELM_RHYDO = 927,
	//SI_HELM_TURISUS = 928,
	//SI_HELM_HAGALAS = 929,
	//SI_HELM_ISIA = 930,
	//SI_HELM_ASIR = 931,
	//SI_HELM_URJ = 932,
	SI_SUHIDE = 933,

	//SI_DORAM_BUF_01 = 935,
	//SI_DORAM_BUF_02 = 936,
	SI_SPRITEMABLE = 937,
	//SI_AID_PERIOD_RECEIVEITEM = 938,
	//SI_AID_PERIOD_PLUSEXP = 939,
	//SI_AID_PERIOD_PLUSJOBEXP = 940,
	//SI_AID_PERIOD_DEADPENALTY = 941,
	//SI_AID_PERIOD_ADDSTOREITEMCOUNT = 942,

	SI_HISS = 950,

	SI_NYANGGRASS = 952,
	SI_CHATTERING = 953,

	SI_GROOMING = 961,
	SI_PROTECTIONOFSHRIMP = 962,
	//SI_EP16_2_BUFF_SS = 963,
	//SI_EP16_2_BUFF_SC = 964,
	//SI_EP16_2_BUFF_AC = 965,
	//SI_GS_MAGICAL_BULLET = 966,

	//SI_FALLEN_ANGEL = 976,

	//SI_AID_PERIOD_RECEIVEITEM_2ND = 983,
	//SI_AID_PERIOD_PLUSEXP_2ND = 984,
	//SI_AID_PERIOD_PLUSJOBEXP_2ND = 985,
	//SI_PRONTERA_JP = 986,

	//SI_GLOOM_CARD = 988,
	//SI_PHARAOH_CARD = 989,
	//SI_KIEL_CARD = 990,

	//SI_CHEERUP = 992,

	//SI_S_MANAPOTION = 995,
	//SI_M_DEFSCROLL = 996,

	//SI_AS_RAGGED_GOLEM_CARD = 1000,
	//SI_LHZ_DUN_N1 = 1001,
	//SI_LHZ_DUN_N2 = 1002,
	//SI_LHZ_DUN_N3 = 1003,
	//SI_LHZ_DUN_N4 = 1004,
};

// opt1テーブル
enum {
	OPT1_NORMAL			= 0,
	OPT1_STONECURSE 	= 1,
	OPT1_FREEZING		= 2,
	OPT1_STUN			= 3,
	OPT1_SLEEP			= 4,
	OPT1_UNDEAD			= 5,
	OPT1_STONECURSE_ING	= 6,
	OPT1_BURNNING		= 7,
	OPT1_IMPRISON		= 8,
};

// opt2テーブル
enum {
	OPT2_NORMAL			= 0x0,
	OPT2_POISON			= 0x1,
	OPT2_CURSE			= 0x2,
	OPT2_SILENCE		= 0x4,
	OPT2_CONFUSION		= 0x8,
	OPT2_BLIND			= 0x10,
	OPT2_ANGELUS		= 0x20,
	OPT2_BLEEDING		= 0x40,
	OPT2_HEAVYPOISON	= 0x80,
	OPT2_FEAR			= 0x100,
};

// opt3テーブル
enum {
	OPT3_NORMAL				= 0x0,
	OPT3_QUICKEN			= 0x1,
	OPT3_OVERTHRUST			= 0x2,
	OPT3_ENERGYCOAT			= 0x4,
	OPT3_EXPLOSIONSPIRITS	= 0x8,
	OPT3_STEELBODY			= 0x10,
	OPT3_BLADESTOP			= 0x20,
	OPT3_AURABLADE			= 0x40,
	OPT3_BERSERK			= 0x80,
	OPT3_LIGHTBLADE			= 0x100,
	OPT3_MOON				= 0x200,
	OPT3_MARIONETTE			= 0x400,
	OPT3_ASSUMPTIO			= 0x800,
	OPT3_SUN_WARM			= 0x1000,
	OPT3_KAITE				= 0x2000,
	OPT3_BUNSIN				= 0x4000,
	OPT3_SOULLINK			= 0x8000,
	OPT3_UNDEAD				= 0x10000,
	OPT3_CONTRACT			= 0x20000,
};

// オプションテーブル
enum {
	OPTION_NOTHING			= 0x0,
	OPTION_SIGHT			= 0x1,
	OPTION_HIDE				= 0x2,
	OPTION_CLOAKING			= 0x4,
	OPTION_PUSHCART			= 0x8,
	OPTION_FALCON			= 0x10,
	OPTION_PECO				= 0x20,
	OPTION_SPECIALHIDING	= 0x40,
	OPTION_PUSHCART2		= 0x80,
	OPTION_PUSHCART3		= 0x100,
	OPTION_PUSHCART4		= 0x200,
	OPTION_PUSHCART5		= 0x400,
	OPTION_CARTMASK			= 0x788,
	OPTION_ORCFACE			= 0x800,
	OPTION_MARRIED			= 0x1000,
	OPTION_RUWACH			= 0x2000,
	OPTION_FOOTPRINT		= 0x4000,
	OPTION_STAR2			= 0x8000,
	OPTION_SANTA			= 0x10000,
	OPTION_TRANSFORM		= 0x20000,
	OPTION_SUMMER			= 0x40000,
	OPTION_DRAGON			= 0x80000,
	OPTION_WUG				= 0x100000,
	OPTION_WUGRIDER			= 0x200000,
	OPTION_MADOGEAR			= 0x400000,
	OPTION_DRAGON2			= 0x800000,
	OPTION_DRAGON3			= 0x1000000,
	OPTION_DRAGON4			= 0x2000000,
	OPTION_DRAGON5			= 0x4000000,
	OPTION_DRAGONMASK		= 0x7880000,
	OPTION_MASK				= 0x7f8d7b8,
};

// Modeテーブル
enum {
	MD_CANMOVE				= 0x001,
	MD_ITEMLOOT				= 0x002,
	MD_AGGRESSIVE			= 0x004,
	MD_FRIENDLINK			= 0x008,
	MD_CASTSENSOR			= 0x010,
	MD_BOSS					= 0x020,
	MD_PLANT				= 0x040,
	MD_CANATTACK			= 0x080,
	MD_CHANGECHASE			= 0x100,
	MD_CHANGETARGET_MELEE	= 0x200,
	MD_CHANGETARGET_CHASE	= 0x400,
	MD_TARGETLOWERLEVEL		= 0x800,
	MD_ANGRY				= 0x1000,
	MD_SKILLIMMUNITY		= 0x2000,
};

// ModeOptテーブル
enum {
	MDOPT_DOUBLE       = 1, // ダブルアタック
	MDOPT_NOATTACK     = 2, // 通常攻撃なし
	MDOPT_FATALBLOW    = 3, // 急所攻撃
	MDOPT_CRITICAL     = 4, // クリティカル攻撃
	MDOPT_PERFECT_FREE = 5, // 完全回避
	MDOPT_STEELCROW    = 6, // スチールクロウ
};

// カートテーブル
enum {
	CART_TYPE_NOTHING	= 0x0,
	CART_TYPE_NORMAL	= 0x1,
	CART_TYPE_LEVEL40	= 0x2,
	CART_TYPE_LEVEL65	= 0x3,
	CART_TYPE_LEVEL80	= 0x4,
	CART_TYPE_LEVEL90	= 0x5,
	CART_TYPE_LEVEL101	= 0x6,
	CART_TYPE_LEVEL111	= 0x7,
	CART_TYPE_LEVEL121	= 0x8,
	CART_TYPE_LEVEL131	= 0x9,
};

#endif
