ifdef SQLFLAG
all: txt-converter
else
all: 
endif

COMMON_SRC = $(shell ls ../common/*.c)

ifeq ($(findstring LOCALZLIB,$(CFLAGS)), LOCALZLIB)
COMMON_SRC += $(shell ls ../common/zlib/*.c)
endif

CONVERTER_SRC = $(shell ls *.c)

txt-converter: $(CONVERTER_SRC:.c=.o) $(COMMON_SRC:.c=.o)
	$(CC) -o ../../$@ $> $(LIBS)

clean:
	rm -f *.o
	rm -f GNUmakefile

ifeq ($(findstring CYGWIN,$(shell uname)), CYGWIN)
	rm -f ../../txt-converter.exe
else
	rm -f ../../txt-converter
endif

