# Makefile for zlib
# Copyright (C) 1995-2003 Jean-loup Gailly.
# For conditions of distribution and use, see copyright notice in zlib.h

OBJS = adler32.o compress.o crc32.o deflate.o trees.o \
       zutil.o inflate.o inftrees.o inffast.o

all: $(OBJS)

